[package]
name = "google-fonts-push"
version = "0.0.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]

[dependencies.git]
git = "https://github.com/stainless-steel/git"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper"
